### ISSUE TITLE
The mocking middleware also records the debug cache header

### ISSUE THREAD

**Issue by OwlyCode** [csarrazi/CsaGuzzleBundle#124]
Hello @csarrazi ! 

I recently wrote some code to dynamically enable/disable the caching middleware based on some conditions. As it is critical, I wrote some functional tests using the mock middleware but realized that the `X-Guzzle-Cache` header is also recorded. So If I want to tell if my middleware was used I cannot tell this from the profiler (`$client->getProfile()->getCollector('guzzle')`).

Luckily I could proxy your middleware but it is far more complex and less convenient than using the profiler : 

```php
$client->getKernel()->setKernelModifier(function ($kernel) use (&$cacheUsed) {
    $originalMiddleware = $kernel->getContainer()->get('csa_guzzle.middleware.cache');

    $kernel->getContainer()->set('cache', function (callable $handler) use ($originalMiddleware, &$cacheUsed) {
        $cacheUsed = true;

        return $originalMiddleware($handler);
    });
})->boot();
```

Is it intended to work this way ?

**Comment by csarrazi** [comment]
Yup. Actually, the `mock` subscriber fetches all headers.
Of course, we could improve this, by ignoring some headers and by providing a blacklist, with default values (`X-Guzzle-Cache`, Symfony debug headers, etc.).

It's something I had in mind for a while already, but didn't have time to work on it, since I have had my hands full with the Ldap component, these last weeks.

**Comment by csarrazi** [comment]
By the way, this is already supported by the MockStorageAdapter (See https://github.com/csarrazi/CsaGuzzleBundle/blob/master/src/GuzzleHttp/Cache/MockStorageAdapter.php#L34).

The only thing needed is to expose a configuration entry, and configure the service accordingly.

**Comment by csarrazi** [comment]
Should be fixed if you use `dev-master`, or `2.1@dev`.

**Comment by csarrazi** [comment]
You can set a headers blacklist, by using:

```yml
csa_guzzle:
    mock:
        enabled: true
        storage_path: '/path/to/mock_folder'
        headers_blacklist: ['X-Guzzle-Cache', 'User-Agent', 'Host']
```

**Comment by OwlyCode** [comment]
Hey, thanks for this feature ! However it doesn't solve the problem : the header is ignored during the generation of the path where the call is recorded, but the header remains in the record.

I checked the code and the blacklist is only used when generating the path, it does not apply to the actual response written into the file.

I will take a look at this and come with something.

**Comment by csarrazi** [comment]
Ok. I will improve this later during the week.

**Comment by csarrazi** [comment]
Can you check now? :)

**Comment by csarrazi** [comment]
Yeah, "today" is also "later this week" ;)

**Comment by csarrazi** [comment]
Ping @OwlyCode

**Comment by OwlyCode** [comment]
I tested it and the headers are no longer recorded, so it works. However I could not make it work with the cache middleware : the header is not there whatever is configured. I'll keep my current workaround and look why later.

**Comment by csarrazi** [comment]
The cache middleware stores all elements from the response, and generate the cache key from all elements of the request (headers, query params, ...). We *could* extend the cache adapter to have the same logic as the Mock middleware (i.e. ignoring headers), and put some logic in common.

I'm not sure I really understand what you are trying to achieve. Regardless, if you want to tell whether your middleware was used or not, I would actually recommend to add a custom header in the response, like the `mock` or `cache` middleware do.

**Comment by OwlyCode** [comment]
The case I am trying to test is if the cache middleware is disabled. Here is the test scenario : 

I enabled caching :
- The mock middleware replays the response from the API
- The cache middleware sets a header (X-Guzzle-Cache)
- I look for the header X-Guzzle-Cache in the profiler and know the cache was used.

I disabled caching : 
- The mock middleware replays the response from the API
- I look for the header X-Guzzle-Cache and know the cache was not used (because it is not set).

In my particular case I made some code that dynamically enables/disables the caching middleware based on some conditions, this is why I want so much to test this.

After some tests, it looks like the cache middleware is never called when the mock middleware is enabled, could it be a middleware priority issue ?

**Comment by OwlyCode** [comment]
I can confirm that if I change the priority of the cache to `-1000` it allows it to triggers before the mock.

**Comment by csarrazi** [comment]
@OwlyCode Indeed. you have run into an issue regarding the priority of the middleware.

**Comment by csarrazi** [comment]
The mock middleware has a higher priority than the cache middleware (-1250 vs -1500).

We could fix this by reducing the priority of the mock middleware.
